### PR TITLE
Trying to figure out a structured way to grab/organize data and code

### PR DESCRIPTION
**Pull request by slin30**
All of this is in-progress. Wanted to get your take on the general organization within an individual's (mine in this case) folder. I'm not a huge fan of using personal cloud storage as a robust means to obtain data, so might optimize that a bit-- might simply drop the csv files into the data folder for this example directly since they are relatively small. 

Mainly interested in whether this approach makes sense. Next steps would be putting together a few scripts to do preprocessing, analysis, viz, etc.

### CODE REVIEW

**Comment by theRanalyst** [comment]
I'll look through and think about it. Also, I don't think you have to do pull requests anymore. I added you as a collaborator to the project, so you should be able to write to the main branch.

**Comment by slin30** [comment]
Yep, noticed that-- just wanted to run this particular thing by you first
as it's along the lines of organization and the like.

**Comment by theRanalyst** [comment]
So, at the end of the day I'm not sure it entirely matters that we all
follow the exact same organizational flow, but to the extent that we might
want to try I've added some files to demonstrate how I would organize the
repo. Essentially all data goes in to the data folder, code in the code
folder. The names of all files, both data and code, begin with the same
word(s) so that they can be correlated together by other users. In my
example, the data is called apache.zip and the first syntax file is called
apacheScraper.R. I then update the readme to document where the data came
from, what it is, what it'll be used for, and any shortfalls there might be
in the data.

That's just how I'd go about it, but we can wait and see what other people
think and make a final decision.

**Comment by slin30** [comment]
That works for me. Will take a look tonight and reconfigure. I've much,
much less experience than you when it comes to these things, so more than
happy to learn/follow your recommendations.

**Pull request merged**
